TILE_SIZE = 32
STEP_SIZE = 20

BOARD_WIDTH = 200
BOARD_HEIGHT = 200
BORDER_WIDTH = STEP_SIZE

EVOLUTIONS = 5
EXPLORATION_RATE = 1
ROLLOUTS = 25
MAX_HITS = 150

DEFAULT_POS = 2 * STEP_SIZE, 2 * STEP_SIZE
GOAL_POS = BOARD_WIDTH - 2 * STEP_SIZE, BOARD_WIDTH - 2 * STEP_SIZE
MOVE_DISTANCE = STEP_SIZE
WIN_DISTANCE = 0

MOVE_CHOICES = [
    (MOVE_DISTANCE, 0),
    (0, MOVE_DISTANCE),
    (0, -MOVE_DISTANCE),
    (-MOVE_DISTANCE, 0),
]
